public class CheckRecursive{
    @TestVisible
    private static boolean run = true;
    @TestVisible
    private static boolean runSec = true;
    @testVisible
    private static boolean runThir = true;
    private static boolean runFour = true;
    private static boolean runFifth = true;
    private static boolean runSixth = true;
    private static boolean runSeven= true;
    @testVisible
    private static boolean runEight= true;
    private static boolean runNine= true;
    @TestVisible
    private static boolean runTen= true;
    private static boolean runEleven= true;
    @TestVisible
    private static boolean runTwelve = true;
    @TestVisible
    private static boolean runThirteen = true;
    @TestVisible
    private static boolean runFourteen = true;
    @TestVisible
    private static boolean runFifteen= true;
    @TestVisible
    private static boolean runSixteen= true;
    @TestVisible
    private static boolean runSeventeen= true;
    private static boolean runNineteen= true;
    private static boolean runEighteen = true;
    @TestVisible
    private static boolean runTwenty = true;
    @TestVisible
    private static boolean runTwentyOne = true;
    @TestVisible
    private static boolean runTwentyTwo = true;
    @TestVisible
    private static boolean runTwentyThree = true;
    @TestVisible
    private static boolean runTwentyFour = true;
    @TestVisible
    private static boolean runTwentyFive = true;
    @TestVisible
    private static boolean runTwentySix = true;
    @TestVisible
    private static boolean runTwentySeven = true;
    @TestVisible
    private static boolean runTwentyEight = true;
    @TestVisible
    private static boolean runTwentyNine = true;
    @TestVisible
    private static boolean runThirty = true;
    @TestVisible
    private static boolean runThirtyOne = true;
    @TestVisible
    private static boolean runThirtyTwo = true;
    
    @TestVisible
    private static boolean runThirtyThree= true;
    @TestVisible
    private static boolean runThirtyFour = true;
    @TestVisible
    private static boolean runThirtyFive = true;
    @TestVisible
    private static boolean runThirtySix = true;
    @TestVisible
    private static boolean runThirtySeven = true;
    @TestVisible
    private static boolean runThirtyEight = true;
    @TestVisible
    private static boolean runThirtyNine = true;
    @TestVisible
    private static boolean runForty = true;
    @TestVisible
    private static boolean runFortyOne = true;
    @TestVisible
    private static boolean runFortyTwo = true;
    @TestVisible
    private static boolean runFortyThree = true;
    @TestVisible
    private static boolean runFortyFour = true;
    @TestVisible
    private static boolean runFortyFive = true;
    @TestVisible
    private static boolean runFortySix = true;
    @TestVisible
    private static boolean runFortySeven = true;
    @TestVisible
    private static boolean runFortyEight = true;
    @TestVisible
    private static boolean runFortyNine = true;
    @TestVisible
    private static boolean runFifty = true;
    @TestVisible
    private static boolean runFiftyOne = true;
    
    public static boolean runOnce(){
        if(run){
            run = false;
            return true;
        }else{
            return run;
        }
    }
    public static boolean runOnceSec(){
        if(runSec){
            runSec = false;
            return true;
        }else{
            return runSec;
        }
    }
    public static boolean runOnceThird(){
        if(runThir){
            runThir= false;
            return true;
        }else{
            return runThir;
        }
    }
    public static boolean runOnceFourth(){
        if(runFour){
            runFour= false;
            return true;
        }else{
            return runFour;
        }
    }
    public static boolean runOnceFifth(){
        if(runFifth){
            runFifth = false;
            return true;
        }else{
            return runFifth;
        }
    }
    public static boolean runOnceSixth(){
        if(runSixth){
            runSixth = false;
            return true;
        }else{
            return runSixth;
        }
    }
    public static boolean runOnceSeventh(){
        if(runSeven){
            runSeven= false;
            return true;
        }else{
            return runSeven;
        }
    }
    public static boolean runOnceEight(){
        if(runEight){
            runEight= false;
            return true;
        }else{
            return runEight;
        }
    }
    public static boolean runOnceNine(){
        if(runNine){
            runNine= false;
            return true;
        }else{
            return runNine;
        }
    }
    
    public static boolean runOnceTen(){
        if(runTen){
            runTen= false;
            return true;
        }else{
            return runTen;
        }
    }
    
    public static boolean runEleven(){
        if(runEleven){
            runEleven = false;
            return true;
        }else{
            return runEleven;
        }
    }
    public static boolean runtwelve(){
        if(runtwelve){
            runtwelve = false;
            return true;
        }else{
            return runtwelve;
        }
    }
    public static boolean runThirteen(){
        if(runThirteen){
            runThirteen= false;
            return true;
        }else{
            return runThirteen;
        }
    }
    public static boolean runFourteen(){
        if(runFourteen){
            runFourteen= false;
            return true;
        }else{
            return runFourteen;
        }
    }
    public static boolean runFifteen(){
        if(runFifteen){
            runFifteen= false;
            return true;
        }else{
            return runFifteen;
        }
    }
    public static boolean runSixteen(){
        if(runSixteen){
            runSixteen= false;
            return true;
        }else{
            return runSixteen;
        }
    }
    
    public static boolean runSeventeen(){
        if(runSeventeen){
            runSeventeen= false;
            return true;
        }else{
            return runSeventeen;
        }
    }
    public static boolean runEighteen(){
        if(runEighteen){
            runEighteen= false;
            return true;
        }else{
            return runEighteen;
        }
    }
    
    public static boolean runNineteen(){
        if(runNineteen){
            runNineteen= false;
            return true;
        }else{
            return runNineteen;
        }
    }
    
    public static boolean runTwenty(){
        if(runTwenty){
            runTwenty= false;
            return true;
        }else{
            return runTwenty;
        }
    }
    public static boolean runTwentyOne(){
        if(runTwentyOne){
            runTwentyOne = false;
            return true;
        }else{
            return runTwentyOne;
        }
    }
    public static boolean runTwentyTwo(){
        if(runTwentyTwo){
            runTwentyTwo = false;
            return true;
        }else{
            return runTwentyTwo;
        }
    }
    public static boolean runTwentyThree(){
        if(runTwentyThree){
            runTwentyThree = false;
            return true;
        }else{
            return runTwentyThree;
        }
    }
    public static boolean runTwentyFour(){
        if(runTwentyFour){
            runTwentyFour= false;
            return true;
        }else{
            return runTwentyFour;
        }
    }
    public static boolean runTwentyFive(){
        if(runTwentyFive){
            runTwentyFive= false;
            return true;
        }else{
            return runTwentyFive;
        }
    }
    public static boolean runTwentySix(){
        if(runTwentySix){
            runTwentySix = false;
            return true;
        }else{
            return runTwentySix;
        }
    }
    public static boolean runTwentySeven(){
        if(runTwentySeven){
            runTwentySeven= false;
            return true;
        }else{
            return runTwentySeven;
        }
    }
    public static boolean runTwentyEight(){
        if(runTwentyEight){
            runTwentyEight = false;
            return true;
        }else{
            return runTwentyEight;
        }
    }
    
    public static boolean runTwentyNine(){
        if(runTwentyNine){
            runTwentyNine = false;
            return true;
        }else{
            return runTwentyNine;
        }
    }
    public static boolean runThirty(){
        if(runThirty){
            runThirty = false;
            return true;
        }else{
            return runThirty ;
        }
    } 
    public static boolean runThirtyOne(){
        if(runThirtyOne){
            runThirtyOne = false;
            return true;
        }else{
            return runThirtyOne;
        }
    } 
    public static boolean runThirtyTwo(){
        if(runThirtyTwo){
            runThirtyTwo = false;
            return true;
        }else{
            return runThirtyTwo;
        }
    }  
    public static boolean runThirtyThree(){
        if(runThirtyThree){
            runThirtyThree = false;
            return true;
        }else{
            return runThirtyThree;
        }
    }
    public static boolean runThirtyFour(){
        if(runThirtyFour){
            runThirtyFour = false;
            return true;
        }else{
            return runThirtyFour;
        }
    }    
    public static boolean runThirtyFive(){
        if(runThirtyFive){
            runThirtyFive = false;
            return true;
        }else{
            return runThirtyFive;
        }
    }
    public static boolean runThirtySix(){
        if(runThirtySix){
            runThirtySix = false;
            return true;
        }else{
            return runThirtySix;
        }
    }
    public static boolean runThirtySeven(){
        if(runThirtySeven){
            runThirtySeven = false;
            return true;
        }else{
            return runThirtySeven;
        }
    }
    public static boolean runThirtyEight(){
        if(runThirtyEight){
            runThirtyEight = false;
            return true;
        }else{
            return runThirtyEight;
        }
    }
    public static boolean runThirtyNine(){
        if(runThirtyNine){
            runThirtyNine = false;
            return true;
        }else{
            return runThirtyNine;
        }
    }
    public static boolean runForty(){
        if(runForty){
            runForty = false;
            return true;
        }else{
            return runForty;
        }
    }
    public static boolean runFortyOne(){
        if(runFortyOne){
            runFortyOne = false;
            return true;
        }else{
            return runFortyOne;
        }
    }
    public static boolean runFortyTwo(){
        if(runFortyTwo){
            runFortyTwo = false;
            return true;
        }else{
            return runFortyTwo;
        }
    }
    public static boolean runFortyThree(){
        if(runFortyThree){
            runFortyThree = false;
            return true;
        }else{
            return runFortyThree;
        }
    }
    public static boolean runFortyFour(){
        if(runFortyFour){
            runFortyFour = false;
            return true;
        }else{
            return runFortyFour;
        }
    }
    public static boolean runFortyFive(){
        if(runFortyFive){
            runFortyFive = false;
            return true;
        }else{
            return runFortyFive;
        }
    }
    public static boolean runFortySix(){
        if(runFortySix){
            runFortySix = false;
            return true;
        }else{
            return runFortySix;
        }
    }
    public static boolean runFortySeven(){
        if(runFortySeven){
            runFortySeven = false;
            return true;
        }else{
            return runFortySeven;
        }
    }
    public static boolean runFortyEight(){
        if(runFortyEight){
            runFortyEight = false;
            return true;
        }else{
            return runFortyEight;
        }
    }
    public static boolean runFortyNine(){
        if(runFortyNine){
            runFortyNine = false;
            return true;
        }else{
            return runFortyNine;
        }
    }
    public static boolean runFifty(){
        if(runFifty){
            runFifty = false;
            return true;
        }else{
            return runFifty;
        }
    }
    public static boolean runFiftyOne(){
        if(runFiftyOne){
            runFiftyOne = false;
            return true;
        }else{
            return runFiftyOne;
        }
    }
    
    public static Set<Id> SetOfIDs = new Set<Id>();
}